# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

 # CONSTANTS
    releaseNotesBodyHeader = "What's new:"
    releaseNotesFileBody = "../app/version/release-notes"
    releaseNotesLocales= ["en-US", "en-GB", "en-CA"]
    releaseNotesMaxLength = 500
    errorMessageCancelled = "Release cancelled 😢"
    aarbExecutable = "AndroidAsanaBridge"
    asanaBridgeInstallationProblem = "Android Asana Release Bridge not installed or configured correctly - see https://app.asana.com/0/0/1203116937958001/f for instructions"

default_platform(:android)

platform :android do

    desc "Deploy APK to GitHub"
    lane :test_apk_download do

      apkPath = "app/build/outputs/apk/play/release/duckduckgo-5.214.1.6-play-release.apk"

      download_universal_apk_from_google_play(
          version_code: 52141006,
          destination: apkPath
      )

      end

    private_lane :"convert_version" do |options|
        original = options[:release_number]
        major, minor, patch = original.downcase.split('.')
        major = major.to_i
        minor = minor.to_i
        patch = patch.to_i
        (major * 10_000_000) + (minor * 10_000) + (patch * 1_000)
    end




end